---
- name: Download and unzip
  hosts: vlad
  become: yes
  tasks:

  - name: download
    ansible.builtin.get_url:
      url: https://dlcdn.apache.org/kafka/3.9.1/kafka-3.9.1-src.tgz
      dest: /home/ansible/kafka
      mode: '0440'
    register: download_result


  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /home/ansible/kafka
      dest: /home/ansible/
      remote_src: yes

