---
- name: Install and enable tuned service
  hosts: all
  become: true
  tasks:
    - name: Install tuned package
      ansible.builtin.apt:
        name: tuned
        state: present
        update_cache: yes
      

    - name: Ensure tuned service is started and enabled
      ansible.builtin.systemd:
        name: tuned
        state: started
        enabled: yes
