---
- name: Install Apache web server
  ansible.builtin.yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Apache web server
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Gather disk facts
  ansible.builtin.setup:
    gather_subset:
      - hardware
      - network
      - virtual
      - devices
  # Это нужно для получения информации о дисках

- name: Определить размер диска sda в GB
  set_fact:
    sda_size_raw: "{{ ansible_devices['sda'].size | default('0 GB') }}"

- name: Конвертировать размер sda_size_raw в число (GB)
  set_fact:
    sda_size_gb: >-
      {% set parts = sda_size_raw.split() %}
      {% set size = parts[0] | float %}
      {% set unit = parts[1] if parts|length > 1 else 'GB' %}
      {% if unit == 'TB' %}
        {{ size * 1024 }}
      {% elif unit == 'GB' %}
        {{ size }}
      {% elif unit == 'MB' %}
        {{ size / 1024 }}
      {% else %}
        {{ size }}
      {% endif %}




  

- name: Create custom index.html with system info
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ apache_docroot }}/index.html"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache

- name: Open port 80 in firewall (firewalld) on RedHat family
  ansible.builtin.firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes
  when: ansible_os_family == "RedHat"
  become: true

- name: Проверить, установлен ли ufw
  ansible.builtin.package_facts:

- name: Проверить, активен ли ufw
  ansible.builtin.shell: ufw status
  register: ufw_status
  changed_when: false
  failed_when: false
  when: "'ufw' in ansible_facts.packages"

- name: Открыть порт 80 в ufw, если ufw установлен и активен, и порт не открыт
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp
  when:
    - "'ufw' in ansible_facts.packages"
    - "'active' in ufw_status.stdout"
    - "'80/tcp' not in ufw_status.stdout"


- name: Ensure Apache service is started and enabled (RedHat)
  ansible.builtin.systemd:
    name: httpd
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Ensure Apache service is started and enabled (Debian)
  ansible.builtin.systemd:
    name: apache2
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Check HTTP response code from localhost
  ansible.builtin.uri:
    url: "http://localhost"
    status_code: 200
  register: result

- name: Fail if HTTP response is not 200
  ansible.builtin.fail:
    msg: "Apache web server is not responding with 200 OK"
  when: result.status != 200
